language: node_js
node_js:
  - "8"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
 - yarn build:production
 - yarn test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
 - yarn build-storybook

deploy:
  - provider: script
    script: yarn semantic-release
    skip-cleanup: true
    on:
      branch: master
  - provider: pages
    local-dir: "./storybook-static"
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    on:
      branch: master
